apiVersion: v1
kind: Service
metadata:
  name: json-storage-service
spec:
  selector:
    app: json-storage-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
